M48
; DRILL file {KiCad (6.0.7)} date Fri Oct 27 20:14:33 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-27T20:14:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X104.0Y-54.0
X104.0Y-116.0
X196.0Y-54.0
X196.0Y-116.0
T2
X139.5Y-84.858
X169.5Y-84.858
T0
M30
